steps:
- name: 'gcr.io/cloud-builders/gradle'
  args:
  - 'clean'
  - 'build'
- name: 'gcr.io/cloud-builders/docker'
  args: 
  - 'build'
  - '--tag=gcr.io/$PROJECT_ID/bookinfo-reviews:$TAG_NAME'
  - '--build-arg=service_version=$TAG_NAME'
  - '.'
  dir: 'reviews-wlpcfg'
- name: 'gcr.io/cloud-builders/docker'
  args: 
  - 'build'
  - '--tag=gcr.io/$PROJECT_ID/bookinfo-reviews:v2.0.0'
  - '--build-arg=service_version=v2'
  - '--build-arg=enable_ratings=true'
  - '.'
  dir: 'reviews-wlpcfg'
- name: 'gcr.io/cloud-builders/docker'
  args: 
  - 'build'
  - '--tag=gcr.io/$PROJECT_ID/bookinfo-reviews:v3.0.0'
  - '--build-arg=service_version=v3'
  - '--build-arg=enable_ratings=true'
  - '--build-arg=star_color=red'
  - '.'
  dir: 'reviews-wlpcfg'

images:
- 'gcr.io/$PROJECT_ID/bookinfo-reviews:$TAG_NAME'
- 'gcr.io/$PROJECT_ID/bookinfo-reviews:v2.0.0'
- 'gcr.io/$PROJECT_ID/bookinfo-reviews:v3.0.0'
