steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '--tag=gcr.io/$PROJECT_ID/bookinfo-ratings:$TAG_NAME', '--build-arg', 'service_version=$TAG_NAME', '.']
images: ['gcr.io/$PROJECT_ID/bookinfo-ratings:$TAG_NAME']
